language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "6f31bdabd265df34539600cb15d97ba04872c3be"
  local_dir: dist
  on:
    branch: master
